language: go

go:
  - 1.15.x

before_script:
  - go mod vendor

script:
  - make lint
  - make test-coverage
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: make build-docker
    on:
      tag: true
  - provider: script
    script: bash scripts/publish-docker.sh
    on:
      tag: true
  - provider: script
    script: make build-release
    on:
      tag: true
  - provider: releases
    api_key:
      secure: $GITHUB_OAUTH_TOKEN
    file:
      - bin/orion.exe
      - bin/orion.darwin
      - bin/orion.linux
    skip_cleanup: true
    draft: true
    on:
      tags: true
branches:
  only:
    # Pushes and PR to the master branch
    - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys when
    # a new tag is pushed. Version tags should be of the form: v0.1.0
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: change
    on_failure: always

