language: go

go:
  - 1.15.x

before_script:
  - go mod vendor

script:
  - make lint
  - make test-coverage
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - go mod vendor
deploy:
  - provider: script
    skip_cleanup: true
    script: make build-release
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    draft: true
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - bin/orion.exe
      - bin/orion.darwin
      - bin/orion.linux
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: make build-docker
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash scripts/publish-docker.sh
    on:
      tags: true

notifications:
  email:
    on_success: change
    on_failure: always

