language: go

go:
  - 1.15.x

script:
  - make test-coverage
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always